BancaProject-web/src/main/java/com/sib/cobro/CobroViewPopupBean.java
package com.sib.cobro;

import com.sib.bs.responses.CobroVistaDetalleResponse;
import com.sib.ejb.dao.CobroDao;
import com.sib.entity.CobroVistaDetalle;
import com.sib.ui.models.CobroCustomEntityModel;
import com.sib.ui.models.CobroModel;
import com.sib.ui.models.CobroVistaDetalleModel;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ActionEvent;
import org.apache.log4j.Logger;

/**
 *
 * @author Snailin Inoa
 */
@ManagedBean(name = "cobroViewPopupBean")
@ViewScoped
public class CobroViewPopupBean extends CobroAbstractPopup implements Serializable {

    public static final Logger LOGGER = Logger.getLogger(CobroViewPopupBean.class);

    @EJB
    CobroDao cobroDao;

    private CobroCustomEntityModel cobroCustomEntityModel;

    private List<CobroVistaDetalleModel> cobroVistaDetalleList;

    public CobroCustomEntityModel getCobroCustomEntityModel() {
        return cobroCustomEntityModel;
    }

    public void setCobroCustomEntityModel(CobroCustomEntityModel cobroCustomEntityModel) {
        this.cobroCustomEntityModel = cobroCustomEntityModel;
    }

    public List<CobroVistaDetalleModel> getCobroVistaDetalleList() {
        if (cobroVistaDetalleList == null) {
            loadList();
        }
        return cobroVistaDetalleList;
    }

    public void setCobroVistaDetalleList(List<CobroVistaDetalleModel> cobroVistaDetalleList) {
        this.cobroVistaDetalleList = cobroVistaDetalleList;
    }

    public void loadList() {
        LOGGER.info("loadList() :: START");
        cobroVistaDetalleList = new ArrayList<CobroVistaDetalleModel>();
        try {
            CobroVistaDetalleResponse cobroVistaDetalleResponse = cobroDao.getCobroVistaDetalleList(cobroCustomEntityModel.getCobroId(), null);

            if (cobroVistaDetalleResponse.getMsgEnum().getCode() == 1) {
                if (cobroVistaDetalleResponse.getCobroVistaDetalleList() != null && !cobroVistaDetalleResponse.getCobroVistaDetalleList().isEmpty()) {
                    LOGGER.info("CobroVistaDetalleList Size :: " + cobroVistaDetalleResponse.getCobroVistaDetalleList().size());
                    CobroUtil cobroUtil = new CobroUtil();
                    for (CobroVistaDetalle cobroVistaDetalle : cobroVistaDetalleResponse.getCobroVistaDetalleList()) {
                        CobroVistaDetalleModel model = cobroUtil.convertirCobroVistaDetalleACobroVistaDetalleModel(cobroVistaDetalle);
                        cobroVistaDetalleList.add(model);

                    }

                }

            }

        } catch (Exception e) {
            LOGGER.info("Error populando la lista de Cobro Vista Detalle :: " + e);
        }
        LOGGER.info("loadList() :: END");
    }

    @Override
    public void execute(ActionEvent event) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cancelProcess(ActionEvent event) {
        this.reset();

    }

    @Override
    public void reset() {
        cobroVistaDetalleList = null;
        cobroCustomEntityModel = null;
    }

    @Override
    public boolean validateFields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String getFileName() {
        return "cobroviewpopup";
    }

    @Override
    public String getPopupTitle() {
        return "Vista Detalle Cobro Historial";
    }

    public void initialize(ActionEvent event) {
        LOGGER.info("initialize() :: START");
        this.reset();
        CobroCustomEntityModel cobro = (CobroCustomEntityModel) event.getComponent().getAttributes().get("cobro");
        LOGGER.info("Cobro :: " + cobro);
        if (cobro != null) {
            this.cobroCustomEntityModel = cobro;
        }
        LOGGER.info("initialize() :: END");
    }
}

BancaProject-web/src/main/java/com/sib/interfaces/IBean.java
package com.sib.interfaces;

import javax.faces.event.ActionEvent;

/**
 *
 * @author Snailin Inoa
 */
public interface IBean {

    public void resetBean();

    public String getFileName();
    
    public void navigate(ActionEvent event);
}

BancaProject-web/src/main/java/com/sib/juego/JuegoModelBean.java
package com.sib.juego;

import com.sib.bs.responses.JuegoResponse;
import com.sib.bs.responses.MessageEnum;
import com.sib.ejb.dao.JuegoDao;
import com.sib.ejb.dao.LoteriaJuegoDao;
import com.sib.entity.Juego;
import com.sib.interfaces.IModelBean;
import com.sib.ui.enums.StatusEnum;
import com.sib.ui.models.JuegoModel;
import com.sib.ui.models.ResponseModel;
import com.sib.util.MessageDisplayUtils;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import org.apache.log4j.Logger;

/**
 *
 * @author Omar Moronta
 */
@ManagedBean(name = "juegoModelBean")
@ViewScoped
public class JuegoModelBean implements IModelBean, Serializable {

    public static final Logger LOG
            = Logger.getLogger(JuegoModelBean.class.getName());

    @EJB
    private JuegoDao juegoDao;
    
    @EJB
    private LoteriaJuegoDao loteriaJuegoDao;
  
    private List<JuegoModel> result = null;

    public JuegoModelBean() {
    }

    private void init() {
        JuegoResponse out = juegoDao.getJuegos(null);

        result = new ArrayList<JuegoModel>();

        if (out != null) {
            if (out.getMsgEnum().equals(MessageEnum.SUCCESS)) {
                List<Juego> juegoOrig = out.getJuegos();

                if (juegoOrig != null) {
                    JuegoUtil juegoUtil = new JuegoUtil();
                    for (Juego j : juegoOrig) {
                        JuegoModel cur = juegoUtil.convertirJuegoAJuegoModel(j);
                        result.add(cur);
                    }
                }
            } else {
                this.displayErrorMessageFromBundle("sab.juego.error.lbl",
                        JuegoConstantes.TABLA_MESSAGE_CLIENT_ID);
            }
        }

    }

    public List<JuegoModel> getJuegoList() {
        if (result == null) {
            init();
        }
        return result;
    }

    public ResponseModel crearJuego(JuegoModel juegoModel) {
        ResponseModel resp = new ResponseModel();

        try {
            JuegoUtil juegoUtil = new JuegoUtil();
            Juego juego = juegoUtil.convertirJuegoModelAJuego(juegoModel);
            LOG.info("Inicio crear Juego..");
            JuegoResponse out = this.juegoDao.crearJuego(juego);
            resp = processResponse(out, "sab.juego.agregar.success",
                    "sab.juego.agregar.error", "sab.juego.agregar.val.error");
            LOG.info("Fin crear Juego..");
        } catch (Exception ex) {
            resp.setWasSuccessful(false);
            resp.setMessage(this.getMessageFromBundle("sab.juego.agregar.error"));            
            LOG.error("Error invocando a JuegoDao para crear juego."
                    + ex.getMessage(), ex);
        }

        return resp;
    }

    public ResponseModel eliminarJuego(JuegoModel juegoModel) {

        ResponseModel resp = new ResponseModel();

        try {
            JuegoUtil juegoUtil = new JuegoUtil();
            Juego juego = juegoUtil.convertirJuegoModelAJuego(juegoModel);
            LOG.info("Inicio eliminar Juego..");
            JuegoResponse out = this.juegoDao.deleteJuego(juego);
            resp = processResponse(out, "sab.juego.eliminar.success",
                    "sab.juego.eliminar.error", "sab.juego.eliminar.val.error");
            LOG.info("Fin eliminar Juego..");
        } catch (Exception ex) {
            resp.setWasSuccessful(false);
            resp.setMessage(this.getMessageFromBundle("sab.juego.eliminar.error"));            
            LOG.error("Error invocando a JuegoDao para eliminar juego."
                    + ex.getMessage(), ex);
        }

        return resp;
    }

    public ResponseModel actualizarJuego(JuegoModel juegoModel) {

        ResponseModel resp = new ResponseModel();

        try {
            JuegoUtil juegoUtil = new JuegoUtil();
            Juego juego = juegoUtil.convertirJuegoModelAJuego(juegoModel);
            LOG.info("Inicio actualizar Juego..");
            LOG.info("Actualizando juego con Id: " + juego.getId());
            JuegoResponse out = this.juegoDao.editarJuego(juego);
            resp = processResponse(out, "sab.juego.actualizar.success",
                    "sab.juego.actualizar.error", "sab.juego.actualizar.val.error");
            LOG.info("Fin actualizar Juego..");
        } catch (Exception ex) {
            resp.setWasSuccessful(false);
            resp.setMessage(this.getMessageFromBundle("sab.juego.actualizar.error"));          
            LOG.error("Error invocando a JuegoDao para actualizar juego."
                    + ex.getMessage(), ex);
        }

        return resp;
    }

    public List<JuegoModel> getJuegosNotRelatedToLoteria(int loteriaId){
        List<JuegoModel> results = null;
        
        JuegoResponse out = juegoDao.getJuegosNOtRelatedInLJByLoteria(loteriaId);

        if (out != null) {
            if (out.getMsgEnum().equals(MessageEnum.SUCCESS)) {
                results = new ArrayList<JuegoModel>();
                List<Juego> juegosOrig = out.getJuegos();

                if (juegosOrig != null) {
                    JuegoUtil gUtil = new JuegoUtil();
                    for (Juego g : juegosOrig) {
                        JuegoModel cur = gUtil.convertirJuegoAJuegoModel(g);
                        results.add(cur);
                    }
                }
            } else {
                LOG.error("Ha ocurrido un error obteniendo Juegos no relacionados"
                        + "a Lotería por codigo de Lotería. "
                        + "Message Enum equals:>"+out.getMsgEnum());
            }
        }
        
        return results;
    }
    
    public List<JuegoModel> getJuegosByLoteriaId(int loteriaId){
        List<JuegoModel> results = null;
        
        JuegoResponse out = loteriaJuegoDao.getJuegosByLoteriaId(loteriaId, 
                StatusEnum.ACTIVO.getStatusLiteral());

        if (out != null) {
            if (out.getMsgEnum().equals(MessageEnum.SUCCESS)) {
                results = new ArrayList<JuegoModel>();
                List<Juego> juegosOrig = out.getJuegos();

                if (juegosOrig != null) {
                    JuegoUtil gUtil = new JuegoUtil();
                    for (Juego g : juegosOrig) {
                        JuegoModel cur = gUtil.convertirJuegoAJuegoModel(g);
                        results.add(cur);
                    }
                }
            } else {
                LOG.error("Ha ocurrido un error obteniendo Juegos por loteria"
                        + "Message Enum equals:>"+out.getMsgEnum());
            }
        }
        
        return results;
    }
    
    /**
     * Este método retornará la lista de juegos para una lotería X que no esté
     * relacionada a una banca y en Banca-Loteria-Juego.
     * 
     * @param loteriaId
     * @return 
     */
    public List<JuegoModel> getJuegosFromLoteriaNotInBLJ(int loteriaId, int bancaId){
        List<JuegoModel> results = null;
        
        JuegoResponse out = juegoDao.getJuegosByLoteriaNotRInBLJ(loteriaId,bancaId);

        if (out != null) {
            if (out.getMsgEnum().equals(MessageEnum.SUCCESS)) {
                results = new ArrayList<JuegoModel>();
                List<Juego> juegosOrig = out.getJuegos();

                if (juegosOrig != null) {
                    JuegoUtil gUtil = new JuegoUtil();
                    for (Juego g : juegosOrig) {
                        JuegoModel cur = gUtil.convertirJuegoAJuegoModel(g);
                        results.add(cur);
                    }
                }
            } else {
                LOG.error("Ha ocurrido un error obteniendo Juegos no relacionados"
                        + "a Lotería en Banca-Loteria-Juego. "
                        + "Message Enum equals:>"+out.getMsgEnum());
            }
        }
        
        return results;
    }    
    
    @Override
    public void resetModelBean() {
        result = null;
    }

    protected void displayErrorMessageFromBundle(String msgproperty, String msgClientId) {
        MessageDisplayUtils.INSTANCE.printErrorMessageFromBundle(msgClientId,
                msgproperty);
    }

    protected String getMessageFromBundle(String msgproperty, Object... params) {
        return MessageDisplayUtils.INSTANCE.
                getMessageFromBundle(msgproperty, params);
    }

    private ResponseModel processResponse(JuegoResponse response,
            String succesMessage, String failureMessage, String validationFailMessage) {

        ResponseModel resp = new ResponseModel();

        if (response != null) {
            /**
             * In this switch the FAIL enum will be treated as default for
             * displaying general message.
             */
            switch (response.getMsgEnum()) {

                case SUCCESS:
                    resp.setWasSuccessful(true);
                    resp.setMessage(
                            getMessageFromBundle(succesMessage));
                    resetModelBean();
                    break;

                case VALIDATION:
                    resp.setWasSuccessful(false);
                    resp.setMessage(getMessageFromBundle(validationFailMessage));
                    break;

                default:
                    resp.setWasSuccessful(false);
                    resp.setMessage(
                            getMessageFromBundle(failureMessage));
                    break;
            }
        } else {
            resp.setWasSuccessful(false);
            resp.setMessage(
                    getMessageFromBundle(failureMessage));

        }

        return resp;

BancaProject-web/src/main/webapp/mantenimiento/juego/home.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"   
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="../../layout/master.xhtml">	

    <ui:define name="content">
        <ui:include src="./juego.xhtml"/>
    </ui:define>
</ui:composition>

BancaProject-web/src/main/webapp/mantenimiento/juego/juego.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    
    <div style="padding-bottom: 20px;">
        <p:outputLabel styleClass="banca-section-title" 
                       value="#{sabmsg['sab.juego.mantenimiento.lbl']}"/>
    </div>
    
    <h:form id="mantjuegoform" prependId="false">

        <div style="padding-bottom: 8px;">
            <p:commandButton value="#{sabmsg['sab.juego.agregar.lbl']}"
                             title="#{sabmsg['sab.juego.agregar.lbl']}"
                             styleClass="banca-buttons" update="juegdialog"
                             actionListener="#{juegoBean.openCreatePopup}"
                             oncomplete="openDialogoJuego();"/>
        </div>

        <div class="banca-mantenimiento-tbl-msg-div banca-mantenimiento-tbl-msg-font">
            <p:messages id="grow" autoUpdate="true" for="juegomantmsg"/>
        </div>
        <p:dataTable id="juegoDT" style="width: 800px;font-size:12px;"
                     paginator="true" rows="10" var="juego" sortMode="single"
                     value="#{juegoBean.modelBean.juegoList}" styleClass="banca-table"
                     paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"  
                     rowsPerPageTemplate="5,10,15">
            <p:column headerText="#{sabmsg['sab.codigo.lbl']}"
                      sortBy="codigo">  
                <h:outputText value="#{juego.codigo}" />  
            </p:column> 

            <p:column headerText="#{sabmsg['sab.nombre.lbl']}"
                      sortBy="nombre">  
                <h:outputText value="#{juego.nombre}" />  
            </p:column> 
            
            <p:column headerText="#{sabmsg['sab.status.lbl']}"
                      sortBy="status">  
                <h:outputText value="#{juego.status}" />  
            </p:column> 

            <p:column headerText="#{sabmsg['sab.fecha.creacion']}"
                      sortBy="fechaCreacion">  
                <h:outputText value="#{juego.fechaCreacion}">
                    <f:convertDateTime pattern="dd-MM-yyyy"/>
                </h:outputText>  
            </p:column>

            <p:column headerText="#{sabmsg['sab.fecha.actualizado']}"
                      sortBy="fechaActualizacion">  
                <h:outputText value="#{juego.fechaActualizacion}">
                    <f:convertDateTime pattern="dd-MM-yyyy"/>
                </h:outputText>
            </p:column>
            
            <p:column headerText="#{sabmsg['sab.operaciones.lbl']}"
                      styleClass="banca-txt-align-center">  
                <p:commandLink title="#{sabmsg['sab.juego.actualizar.lbl']}"
                               actionListener="#{juegoBean.openUpdatePopup}"
                               update=":mantjuegoform:juegdialog"
                               oncomplete="openDialogoJuego();">
                    <img src="../../resources/images/edit-notes.png" 
                         style="height:20px;width: 20px;"/>
                    <f:param value="#{juego.id}" name="juegoId"/>
                </p:commandLink>
                <h:outputText value="&#160;" />
                <h:outputText value="&#160;" /> 
                <p:commandLink title="#{sabmsg['sab.juego.eliminar.lbl']}"
                               actionListener="#{juegoBean.openDeletePopup}"
                               oncomplete="openDialogoJuego();"
                               update=":mantjuegoform:juegdialog"
                               styleClass="banca-non-txt-decoration">
                    <img src="../../resources/images/delete.png" 
                         style="height:20px;width: 20px;"/>
                    <f:param value="#{juego.id}" name="juegoId"/>
                </p:commandLink>                
            </p:column>            
        </p:dataTable>          
    
        <ui:include src="./juegopopup.xhtml"/>
        
        <p:remoteCommand name="updateJuegoAll" update="juegoDT" process="juegoDT"
                         ignoreAutoUpdate="true"/>
    </h:form>
    <script>
        function openDialogoJuego(){
            PF('juegodlg').show();
        }
        
        function closeDialogoJuego(){
            PF('juegodlg').hide(); 
        }
        
        function handleJuegoOperationResponse(xhr, status, args) { 
            if(args){
                if(args.operationStatus==="000"){
                    closeDialogoJuego();
                    updateJuegoAll();
                }else if(args.operationStatus==="001"){
                    
                }
            }
        }
    </script>
</ui:composition>

BancaProject-web/src/main/webapp/mantenimiento/juego/juegocreatepopup.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    
    <span class="red-text bold-text">*</span>
    <h:outputLabel escape="true" value="&#160;"/> #{sabmsg['sab.campos.requeridos']}
        
    <h:panelGrid columns="3" cellpadding="3" cellspacing="1" 
                 style="padding-top: 15px;  padding-bottom:30px;" width="100%">
        <h:outputLabel styleClass="red-text bold-text" value="*"/>
        <h:outputLabel value="#{sabmsg['sab.codigo.lbl']}" 
                       styleClass="banca-popup-field-name "/>
        <h:inputText value="#{juegoBean.popupHandler.model.codigo}"
                     size="20"/>

        <h:outputLabel styleClass="red-text bold-text" value="*"/>
        <h:outputLabel value="#{sabmsg['sab.nombre.lbl']}" 
                       styleClass="banca-popup-field-name"/> 
        <h:inputText value="#{juegoBean.popupHandler.model.nombre}"
                     size="30"/>        
    </h:panelGrid>
    <p:separator/>
    <p:commandButton value="#{sabmsg['sab.agregar.lbl']}" styleClass="fltRight"
                     title="#{sabmsg['sab.agregar.lbl']}" 
                     actionListener="#{juegoBean.popupHandler.execute}"
                     oncomplete="handleJuegoOperationResponse(xhr, status, args);"/>    
    <p:commandButton value="#{sabmsg['sab.cancelar.lbl']}" styleClass="fltRight"
                     title="#{sabmsg['sab.cancelar.lbl']}" update="juegdialog"
                     actionListener="#{juegoBean.popupHandler.cancelProcess}"
                     oncomplete="closeDialogoJuego();"/>
    <div class="clear"/>
</ui:composition>

BancaProject-web/src/main/webapp/mantenimiento/juego/juegodeletepopup.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    
    <h:outputText styleClass="bold-text " value="#{sabmsg['sab.eliminar.juego']}"/>
    <br/>
    
    <h:panelGrid columns="2" style="padding-top:10px;">
        <h:outputText styleClass="bold-text banca-font-size-13" 
                      value="#{sabmsg['sab.codigo.lbl']}"/>
        <h:outputText  value="#{juegoBean.popupHandler.model.codigo}"/>
        
        <h:outputText styleClass="bold-text banca-font-size-13" 
                      value="#{sabmsg['sab.nombre.lbl']}"/>
        <h:outputText  value="#{juegoBean.popupHandler.model.nombre}"/>
        
        <h:outputText styleClass="bold-text banca-font-size-13" 
                      value="#{sabmsg['sab.status.lbl']}"/>
        <h:outputText  value="#{juegoBean.popupHandler.model.status}"/>
    </h:panelGrid>    
    <br/>
    <h:outputText styleClass="bold-text banca-font-size-11" 
                  value="#{sabmsg['sab.eliminar.juego.nota']}"
                  style="padding-bottom:15px;padding-top:10px;"/>
    <p:separator/>
    <p:commandButton value="#{sabmsg['sab.eliminar.lbl']}" styleClass="fltRight"
                     title="#{sabmsg['sab.eliminar.lbl']}"
                     actionListener="#{juegoBean.popupHandler.execute}"
                     oncomplete="handleJuegoOperationResponse(xhr, status, args);"/>    
    <p:commandButton value="#{sabmsg['sab.cancelar.lbl']}" styleClass="fltRight"
                     title="#{sabmsg['sab.cancelar.lbl']}" update="juegdialog"
                     actionListener="#{juegoBean.popupHandler.cancelProcess}"
                     oncomplete="closeDialogoJuego();"/>
    <div class="clear"/>    
</ui:composition>

BancaProject-web/src/main/webapp/mantenimiento/juego/juegopopup.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:dialog widgetVar="juegodlg" showHeader="false" dynamic="true"
              modal="true" closable="true" resizable="false" position="center"
              id="juegdialog" style="min-width: 400px; max-width: 500px;">
        <h:panelGrid columns="2" width="100%">
            <h3 class="fltLeft">
                #{juegoBean.popupHandler.popupTitle}
            </h3>
            <p:commandLink update="juegdialog" oncomplete="closeDialogoJuego();"
                actionListener="#{juegoBean.popupHandler.cancelProcess}"
                styleClass="fltRight">
                <img src="../../resources/images/close.png" class="banca-close-dlg-img"/>
            </p:commandLink>
        </h:panelGrid>
        <div class="clear"/>
        <p:outputPanel id="juegodlgbody">
            <div style="padding-bottom: 8px;" class="banca-message-style">
                <p:messages id="msgjuegos" closable="true"
                            autoUpdate="true" for="juegdlg"/>
            </div>

            <div style="font-size:12px;">
                <ui:include src="./#{juegoBean.popupHandler.fileName}.xhtml"/>
            </div>
        </p:outputPanel>    
    </p:dialog>

</ui:composition>

BancaProject-web/src/main/webapp/mantenimiento/juego/juegoupdatepopup.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    
    <span class="red-text bold-text">*</span>
    <h:outputLabel escape="true" value="&#160;"/> #{sabmsg['sab.campos.requeridos']}
        
    <h:panelGrid columns="3" cellpadding="3" cellspacing="1" 
                 style="padding-top: 15px;" width="100%">

        <h:outputLabel styleClass="red-text bold-text" value="*"/>
        <h:outputLabel value="#{sabmsg['sab.nombre.lbl']}" 
                       styleClass="banca-popup-field-name"/> 
        <h:inputText value="#{juegoBean.popupHandler.model.nombre}"
                     size="30"/>
        
        <h:outputLabel escape="true" value="&#160;"/>
        <h:outputLabel value="#{sabmsg['sab.status.lbl']}" 
                       styleClass="banca-popup-field-name"/> 
        <h:selectOneMenu
            value="#{juegoBean.popupHandler.model.status}">
            <f:selectItem itemValue="A" itemLabel="#{sabmsg['sab.activo.lbl']}"/>
            <f:selectItem itemValue="I" itemLabel="#{sabmsg['sab.inactivo.lbl']}"/>
        </h:selectOneMenu>          
    </h:panelGrid>
    <p:separator/>
    <p:commandButton value="#{sabmsg['sab.actualizar.lbl']}" styleClass="fltRight"
                     title="#{sabmsg['sab.actualizar.lbl']}"
                     oncomplete="handleJuegoOperationResponse(xhr, status, args);"
                     actionListener="#{juegoBean.popupHandler.execute}"/>    
    <p:commandButton value="#{sabmsg['sab.cancelar.lbl']}" styleClass="fltRight"
                     title="#{sabmsg['sab.cancelar.lbl']}" update="juegdialog"
                     actionListener="#{juegoBean.popupHandler.cancelProcess}"
                     oncomplete="closeDialogoJuego();"/>
    <div class="clear"/>
</ui:composition>