BancaProject-web/src/main/java/com/sib/reportes/bygrupo/common/GrupoIdBasedAbstractBean.java
package com.sib.reportes.bygrupo.common;

import com.sib.grupo.GrupoModelBean;
import com.sib.ui.enums.StatusEnum;
import com.sib.ui.models.GrupoModel;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedProperty;
import javax.faces.model.SelectItem;

/**
 *
 * @author Omar Moronta
 */
public abstract class GrupoIdBasedAbstractBean implements Serializable {

    int selectedGrupo;
    private List<SelectItem> gruposSI;

    @ManagedProperty(value = "#{grupoModelBean}")
    private GrupoModelBean grupoModelBean;

    public int getSelectedGrupo() {
        return selectedGrupo;
    }

    public void setSelectedGrupo(int selectedGrupo) {
        this.selectedGrupo = selectedGrupo;
    }

    public GrupoModelBean getGrupoModelBean() {
        return grupoModelBean;
    }

    public void setGrupoModelBean(GrupoModelBean grupoModelBean) {
        this.grupoModelBean = grupoModelBean;
    }

    public List<SelectItem> getGruposSI() {
        if (gruposSI == null) {
            List<GrupoModel> gruposActivos
                    = this.grupoModelBean.getGruposByStatus(StatusEnum.ACTIVO.getStatusLiteral());
            gruposSI = new ArrayList<SelectItem>();

            if (gruposActivos != null) {
                for (GrupoModel gm : gruposActivos) {
                    gruposSI.add(new SelectItem(gm.getId(), gm.getCodigo()));
                }
            }
        }
        return gruposSI;
    }

    public void setGruposSI(List<SelectItem> gruposSI) {
        this.gruposSI = gruposSI;
    }

    public abstract void onGrupoSelectionChange();
}

BancaProject-web/src/main/java/com/sib/reportes/bygrupo/common/GrupoIdBasedAbstractInputBean.java
package com.sib.reportes.bygrupo.common;

import java.io.Serializable;

/**
 *
 * @author Omar Moronta
 */
public class GrupoIdBasedAbstractInputBean implements Serializable {

    private int grupoId;

    public int getGrupoId() {
        return grupoId;
    }

    public void setGrupoId(int grupoId) {
        this.grupoId = grupoId;
    }
}

BancaProject-web/src/main/java/com/sib/reportes/bygrupo/gananciaperdida/RepGananciaPerdidaBean.java
package com.sib.reportes.bygrupo.gananciaperdida;

import com.sib.reportes.bygrupo.common.GrupoIdBasedAbstractBean;
import com.sib.ui.models.GananciaPerdidaModel;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import org.primefaces.component.datatable.DataTable;

/**
 *
 * @author Omar Moronta
 */
@ManagedBean(name = "repGananciaPerdidaBean")
@ViewScoped
public class RepGananciaPerdidaBean extends GrupoIdBasedAbstractBean {

    @ManagedProperty(value = "#{repGananciaPerdidaModelBean}")
    private RepGananciaPerdidaModelBean modelBean;

    private DataTable dt;

    List<GananciaPerdidaModel> filteredList;

    /*
     * Asumiendo que el filtro es fechaCreacionFormateada.
     * Pendiente implementar Lazy.
     */
    private static final String FILTRO_LABEL = "fechaCreacionFormateada";

    public RepGananciaPerdidaModelBean getModelBean() {
        return modelBean;
    }

    public DataTable getDt() {
        return dt;
    }

    public void setDt(DataTable dt) {
        this.dt = dt;
    }

    public List<GananciaPerdidaModel> getFilteredList() {
        return filteredList;
    }

    public void setFilteredList(List<GananciaPerdidaModel> filteredList) {
        this.filteredList = filteredList;
    }

    public void setModelBean(RepGananciaPerdidaModelBean modelBean) {
        this.modelBean = modelBean;
    }

    public double getSummaryGanancias() {
        double result = 0;

        if (this.dt.getFilters() != null && !this.dt.getFilters().isEmpty()) {
            String valorFiltrado=this.dt.getFilters().get(FILTRO_LABEL);
            for (GananciaPerdidaModel gpm : this.modelBean.getGananciaPerdidaList()) {
                if (gpm.getFechaCreacionFormateada() != null 
                        && gpm.getFechaCreacionFormateada().startsWith(valorFiltrado)) {
                    result += gpm.getGanancia();
                }
            }
        } else if (this.modelBean.getGananciaPerdidaList() != null
                && !this.modelBean.getGananciaPerdidaList().isEmpty()) {
            for (GananciaPerdidaModel gpm : this.modelBean.getGananciaPerdidaList()) {
                result += gpm.getGanancia();
            }
        }

        return result;
    }

    public double getSummaryPerdidas() {
        double result = 0;
        if (this.dt.getFilters() != null && !this.dt.getFilters().isEmpty()) {
            String valorFiltrado=this.dt.getFilters().get(FILTRO_LABEL);
            for (GananciaPerdidaModel gpm : this.getModelBean().getGananciaPerdidaList()) {
                if (gpm.getFechaCreacionFormateada() != null 
                        && gpm.getFechaCreacionFormateada().startsWith(valorFiltrado)) {
                    result += gpm.getPerdida();
                }
            }
        } else if (this.modelBean.getGananciaPerdidaList() != null
                && !this.modelBean.getGananciaPerdidaList().isEmpty()) {
            for (GananciaPerdidaModel gpm : this.modelBean.getGananciaPerdidaList()) {
                result += gpm.getPerdida();
            }
        }

        return result;
    }

    @Override
    public void onGrupoSelectionChange() {
        this.modelBean.resetModelBean();
    }

}

BancaProject-web/src/main/java/com/sib/reportes/bygrupo/gananciaperdida/RepGananciaPerdidaInputBean.java
package com.sib.reportes.bygrupo.gananciaperdida;

import com.sib.reportes.bygrupo.common.GrupoIdBasedAbstractInputBean;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

/**
 *
 * @author Omar Moronta
 */
@ManagedBean(name = "repGananciaPerdidaInputBean")
@ViewScoped
public class RepGananciaPerdidaInputBean extends GrupoIdBasedAbstractInputBean{

    public RepGananciaPerdidaInputBean() {
    }
}

BancaProject-web/src/main/java/com/sib/reportes/bygrupo/gananciaperdida/RepGananciaPerdidaModelBean.java
package com.sib.reportes.bygrupo.gananciaperdida;

import com.sib.bs.responses.GananciaPerdidaResponse;
import com.sib.bs.responses.MessageEnum;
import com.sib.ejb.dao.DetalleGeneralDao;
import com.sib.entity.GananciaPerdida;
import com.sib.interfaces.IModelBean;
import com.sib.ui.models.GananciaPerdidaModel;
import com.sib.util.MessageDisplayUtils;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import org.apache.log4j.Logger;

/**
 *
 * @author Omar Moronta
 */
@ManagedBean(name = "repGananciaPerdidaModelBean")
@ViewScoped
public class RepGananciaPerdidaModelBean implements IModelBean, Serializable {

    private List<GananciaPerdidaModel> gananciaPerdidaList;

    @EJB
    private DetalleGeneralDao detalleGeneralDao;

    public static final Logger LOG
            = Logger.getLogger(RepGananciaPerdidaModelBean.class.getName());

    @ManagedProperty(value = "#{repGananciaPerdidaInputBean}")
    private RepGananciaPerdidaInputBean inputBean;

    public RepGananciaPerdidaInputBean getInputBean() {
        return inputBean;
    }

    public void setInputBean(RepGananciaPerdidaInputBean inputBean) {
        this.inputBean = inputBean;
    }

    public List<GananciaPerdidaModel> getGananciaPerdidaList() {
        if (gananciaPerdidaList == null) {
            init();
        }
        return gananciaPerdidaList;
    }

    private void init() {
        Integer grupoId = this.inputBean.getGrupoId();
        
        GananciaPerdidaResponse out
                = detalleGeneralDao.getGananciasAndPerdidasByGrupo(grupoId == null ? 0 : grupoId.intValue());

        gananciaPerdidaList = new ArrayList<GananciaPerdidaModel>();

        if (out != null) {

            if (out.getMsgEnum().equals(MessageEnum.SUCCESS)) {
                List<GananciaPerdida> orig = out.getGananciasPerdidas();
                
                if (orig != null) {
                   
                    GananciaPerdidaUtil dgUtil = new GananciaPerdidaUtil();
                    for (GananciaPerdida j : orig) {
                        
                        
                        GananciaPerdidaModel cur = dgUtil.convertirGanPerdAGanPerdModel(j);
                        gananciaPerdidaList.add(cur);
                    }
                    
                }
            } else {
                this.displayErrorMessageFromBundle("sab.reportes.bygrupo.ganper.error.lbl",
                        RepGananciaPerdidaConstantes.TABLA_MESSAGE_CLIENT_ID);
            }
        }

    }

    @Override
    public void resetModelBean() {
        LOG.info("Reseting modelbean ");
        this.gananciaPerdidaList = null;
    }

    protected void displayErrorMessageFromBundle(String msgproperty, String msgClientId) {
        MessageDisplayUtils.INSTANCE.printErrorMessageFromBundle(msgClientId,
                msgproperty);
    }
}

BancaProject-web/src/main/java/com/sib/reportes/bygrupo/montoporcentaje/MontoPorcentajeBean.java
package com.sib.reportes.bygrupo.montoporcentaje;

import com.sib.reportes.bygrupo.common.GrupoIdBasedAbstractBean;
import com.sib.ui.models.PorcentajesModel;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import org.primefaces.component.datatable.DataTable;

/**
 *
 * @author Omar Moronta
 */
@ManagedBean(name = "montoPorcentajeBean")
@ViewScoped
public class MontoPorcentajeBean extends GrupoIdBasedAbstractBean {

    @ManagedProperty(value = "#{montoPorcentajeModelBean}")
    private MontoPorcentajeModelBean modelBean;

    private DataTable dt;

    List<PorcentajesModel> filteredList;

    /*
     * Asumiendo que el filtro es fechaCreacionFormateada.
     * Pendiente implementar Lazy.
     */
    private static final String FILTRO_LABEL = "fechaCreacionFormateada";

    public MontoPorcentajeModelBean getModelBean() {
        return modelBean;
    }

    public void setModelBean(MontoPorcentajeModelBean modelBean) {
        this.modelBean = modelBean;
    }

    public List<PorcentajesModel> getFilteredList() {
        return filteredList;
    }

    public void setFilteredList(List<PorcentajesModel> filteredList) {
        this.filteredList = filteredList;
    }

    public DataTable getDt() {
        return dt;
    }

    public void setDt(DataTable dt) {
        this.dt = dt;
    }

    public double getSummaryTotalBancas() {
        double result = 0;

        if (this.dt.getFilters() != null && !this.dt.getFilters().isEmpty()) {
            String valorFiltrado = this.dt.getFilters().get(FILTRO_LABEL);
            for (PorcentajesModel gpm : this.modelBean.getMontoPorcentajeList()) {
                if (gpm.getFechaCreacionFormateada() != null
                        && gpm.getFechaCreacionFormateada().startsWith(valorFiltrado)) {
                    result += gpm.getTotalBanca();
                }
            }
        } else if (this.modelBean.getMontoPorcentajeList() != null
                && !this.modelBean.getMontoPorcentajeList().isEmpty()) {
            for (PorcentajesModel gpm : this.modelBean.getMontoPorcentajeList()) {
                result += gpm.getTotalBanca();
            }
        }

        return result;
    }

    public double getSummaryTotalJuego1() {
        double result = 0;

        if (this.dt.getFilters() != null && !this.dt.getFilters().isEmpty()) {
            String valorFiltrado = this.dt.getFilters().get(FILTRO_LABEL);
            for (PorcentajesModel gpm : this.modelBean.getMontoPorcentajeList()) {
                if (gpm.getFechaCreacionFormateada() != null
                        && gpm.getFechaCreacionFormateada().startsWith(valorFiltrado)) {
                    result += gpm.getTotalJuego1();
                }
            }
        } else if (this.modelBean.getMontoPorcentajeList() != null
                && !this.modelBean.getMontoPorcentajeList().isEmpty()) {
            for (PorcentajesModel gpm : this.modelBean.getMontoPorcentajeList()) {
                result += gpm.getTotalJuego1();
            }
        }

        return result;
    }

    public double getSummaryTotalJuego2() {
        double result = 0;

        if (this.dt.getFilters() != null && !this.dt.getFilters().isEmpty()) {
            String valorFiltrado = this.dt.getFilters().get(FILTRO_LABEL);
            for (PorcentajesModel gpm : this.modelBean.getMontoPorcentajeList()) {
                if (gpm.getFechaCreacionFormateada() != null
                        && gpm.getFechaCreacionFormateada().startsWith(valorFiltrado)) {
                    result += gpm.getTotalJuego2();
                }
            }
        } else if (this.modelBean.getMontoPorcentajeList() != null
                && !this.modelBean.getMontoPorcentajeList().isEmpty()) {
            for (PorcentajesModel gpm : this.modelBean.getMontoPorcentajeList()) {
                result += gpm.getTotalJuego2();
            }
        }

        return result;
    }

    public double getSummaryTotalJuego3() {
        double result = 0;

        if (this.dt.getFilters() != null && !this.dt.getFilters().isEmpty()) {
            String valorFiltrado = this.dt.getFilters().get(FILTRO_LABEL);
            for (PorcentajesModel gpm : this.modelBean.getMontoPorcentajeList()) {
                if (gpm.getFechaCreacionFormateada() != null
                        && gpm.getFechaCreacionFormateada().startsWith(valorFiltrado)) {
                    result += gpm.getTotalJuego3();
                }
            }
        } else if (this.modelBean.getMontoPorcentajeList() != null
                && !this.modelBean.getMontoPorcentajeList().isEmpty()) {
            for (PorcentajesModel gpm : this.modelBean.getMontoPorcentajeList()) {
                result += gpm.getTotalJuego3();
            }
        }

        return result;
    }

    @Override
    public void onGrupoSelectionChange() {
        this.modelBean.resetModelBean();
    }

}

BancaProject-web/src/main/java/com/sib/reportes/bygrupo/montoporcentaje/MontoPorcentajeInputBean.java
package com.sib.reportes.bygrupo.montoporcentaje;

import com.sib.reportes.bygrupo.common.GrupoIdBasedAbstractInputBean;
import com.sib.util.DateFormatUtil;
import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

/**
 *
 * @author Omar Moronta
 */
@ManagedBean(name = "montoPorcentajeInputBean")
@ViewScoped
public class MontoPorcentajeInputBean extends GrupoIdBasedAbstractInputBean {

    private Date initDate;
    private Date finalDate;

    public MontoPorcentajeInputBean() {
    }

    public Date getInitDate() {
        return initDate;
    }

    public void setInitDate(Date initDate) {
        this.initDate = initDate;
    }

    public Date getFinalDate() {
        return finalDate;
    }

    public void setFinalDate(Date finalDate) {
        this.finalDate = finalDate;
    }

    public String getFormattedInitDate() {
        String result = "";
        if (initDate != null) {
            result = DateFormatUtil.
                    convertDateToStringWithStandardFormat(
                            this.getInitDate());
        }

        return result;
    }

    public String getFormattedFinalDate() {
        String result = "";
        if (finalDate != null) {
            result = DateFormatUtil.
                    convertDateToStringWithStandardFormat(
                            this.getFinalDate());
        }

        return result;
    }

    public void reset() {
        this.setGrupoId(0);
        this.setInitDate(null);
        this.setFinalDate(null);
    }
}

BancaProject-web/src/main/webapp/reportes/bygrupo/porcentaje/home.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="../../../layout/master.xhtml">	
    <ui:define name="content">
        <ui:include src="./porcentaje.xhtml"/>
    </ui:define>
</ui:composition>

BancaProject-web/src/main/webapp/reportes/bygrupo/porcentaje/porcentaje.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <div style="padding-bottom: 28px;">
        <p:outputLabel styleClass="banca-section-title" 
                       value="#{sabmsg['sab.reportes.bygrupo.porc.lbl']}"/>
    </div>

    <h:form id="reptbygrupoporcform" prependId="false">
        <h:panelGrid columns="4">
            <h:outputText styleClass="banca-font-size-18 bold-text"
                          value="#{sabmsg['sab.banca.seleccion.grupo']}" />
            <h:outputText value="&#160;" />
            <h:outputText value="&#160;" />
            <h:selectOneMenu id="grupos"
                             value="#{montoPorcentajeBean.modelBean.inputBean.grupoId}">
                <f:selectItem itemLabel="[Seleccione un Grupo]" itemValue="0"/>  
                <f:selectItems value="#{montoPorcentajeBean.gruposSI}"/>
                <p:ajax listener="#{montoPorcentajeBean.onGrupoSelectionChange()}"
                        event="change" onstart="repPorcDTWidget.clearFilters();" 
                        process="@this repPorcDT" update="repByGrupoPorcOPanel"/>                
            </h:selectOneMenu>
        </h:panelGrid>

        <p:outputPanel id="repByGrupoPorcSumm" style="padding-top: 10px; padding-bottom: 5px;">

            <h:outputText value="#{sabmsg['sab.detalle.grupo.lbl']}" 
                          class="bold-text banca-font-size-14" 
                          style="padding-bottom:10px;"/>

            <table style="padding-top:10px;">
                <tr>
                    <td class="banca-font-size-13 bold-text">#{sabmsg['sab.reportes.bygrupo.porc.gan.totales.grp']}</td>
                    <td class="banca-font-size-12">
                        <h:outputText value="#{montoPorcentajeBean.summaryTotalBancas}">
                            <f:convertNumber type="currency" currencySymbol="$" />
                        </h:outputText>
                    </td>
                </tr>
                <tr style="padding-top:8px;">
                    <td class="banca-font-size-13 bold-text">#{sabmsg['sab.reportes.bygrupo.porc.gan.juego1.grp']}</td>
                    <td class="banca-font-size-12">
                        <h:outputText value="#{montoPorcentajeBean.summaryTotalJuego1}">
                            <f:convertNumber type="currency" currencySymbol="$" />
                        </h:outputText>
                    </td>                    
                </tr>
                <tr>
                    <td class="banca-font-size-13 bold-text">#{sabmsg['sab.reportes.bygrupo.porc.gan.juego2.grp']}</td>
                    <td class="banca-font-size-12">
                        <h:outputText value="#{montoPorcentajeBean.summaryTotalJuego2}">
                            <f:convertNumber type="currency" currencySymbol="$" />
                        </h:outputText>
                    </td>                    
                </tr>
                <tr>
                    <td class="banca-font-size-13 bold-text">#{sabmsg['sab.reportes.bygrupo.porc.gan.juego3.grp']}</td>
                    <td class="banca-font-size-12">
                        <h:outputText value="#{montoPorcentajeBean.summaryTotalJuego3}">
                            <f:convertNumber type="currency" currencySymbol="$" />
                        </h:outputText>
                    </td>                    
                </tr>                
            </table>
        </p:outputPanel>        

        <p:outputPanel id="repByGrupoPorcOPanel" style="padding-top:20px;">

            <div class="banca-mantenimiento-tbl-msg-div banca-mantenimiento-tbl-msg-font">
                <p:messages autoUpdate="true" for="reptByGrupoMontPorctmsg"/>
            </div>            

            <p:dataTable id="repPorcDT" style="width: 100%;font-size:12px;"
                         paginator="true" rows="10" var="porc" sortMode="single"
                         binding="#{montoPorcentajeBean.dt}" 
                         filteredValue="#{montoPorcentajeBean.filteredList}"
                         value="#{montoPorcentajeBean.modelBean.montoPorcentajeList}" 
                         styleClass="banca-table" widgetVar="repPorcDTWidget"
                         paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"  
                         rowsPerPageTemplate="5,10,15">

                <p:ajax event="filter" update=":reptbygrupoporcform:repByGrupoPorcSumm"/>

                <p:column headerText="#{sabmsg['sab.banca.lbl']}"
                          sortBy="banca">  
                    <h:outputText value="#{porc.banca}" />  
                </p:column> 

                <p:column headerText="#{sabmsg['sab.reportes.bygrupo.porc.total.banca.grp']}"
                          sortBy="totalBanca">  
                    <h:outputText value="#{porc.totalBanca}">
                        <f:convertNumber type="currency" currencySymbol="$" />
                    </h:outputText>  
                </p:column> 

                <p:column headerText="#{sabmsg['sab.reportes.bygrupo.porc.total.juego1.grp']}"
                          sortBy="totalJuego1">  
                    <h:outputText value="#{porc.totalJuego1}">
                        <f:convertNumber type="currency" currencySymbol="$" />
                    </h:outputText>  
                </p:column>               

                <p:column headerText="#{sabmsg['sab.reportes.bygrupo.porc.total.juego2.grp']}"
                          sortBy="totalJuego2">  
                    <h:outputText value="#{porc.totalJuego2}">
                        <f:convertNumber type="currency" currencySymbol="$" />
                    </h:outputText>  
                </p:column>

                <p:column headerText="#{sabmsg['sab.reportes.bygrupo.porc.total.juego3.grp']}"
                          sortBy="totalJuego3">  
                    <h:outputText value="#{porc.totalJuego3}" >
                        <f:convertNumber type="currency" currencySymbol="$" />
                    </h:outputText>  
                </p:column>                

                <p:column headerText="#{sabmsg['sab.fecha.agregado']}"
                          sortBy="fecha" filterBy="fechaCreacionFormateada">  
                    <h:outputText value="#{porc.fechaCreacionFormateada}" />  
                </p:column>
            </p:dataTable>            
        </p:outputPanel>

    </h:form>

    <script>
        $(function() {
            $("#reptbygrupoporcform").attr("autocomplete", "off");
        });
        $(document).ready(function() {
            $('#grupos').val(0);
        });
    </script>
</ui:composition>